#!/bin/bash
set -e

CHROOT_DIR=$1
NETWORK_TYPE=$2
IP_ADDRESS=$3
GATEWAY=$4
DNS_SERVERS=$5

if [ -z "$CHROOT_DIR" ] || [ -z "$NETWORK_TYPE" ]; then
    exit 1
fi

echo "Installing network packages..."
chroot "$CHROOT_DIR" bash -c "DEBIAN_FRONTEND=noninteractive apt-get update"
chroot "$CHROOT_DIR" bash -c "DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends iproute2 ifupdown"

mkdir -p "$CHROOT_DIR/etc/network"

if [ "$NETWORK_TYPE" = "dhcp" ]; then
    echo "Configuring network for DHCP"
    
    cat > "$CHROOT_DIR/etc/network/interfaces" << EOF
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
EOF

elif [ "$NETWORK_TYPE" = "static" ]; then
    if [ -z "$IP_ADDRESS" ] || [ -z "$GATEWAY" ]; then
        echo "Error: Static network configuration requires IP address and gateway"
        exit 1
    fi
    
    echo "Configuring static network: IP=$IP_ADDRESS, Gateway=$GATEWAY"

    NETMASK="255.255.255.0"
    if [[ "$IP_ADDRESS" == */* ]]; then
        CIDR=$(echo "$IP_ADDRESS" | cut -d'/' -f2)
        IP_ADDRESS=$(echo "$IP_ADDRESS" | cut -d'/' -f1)

        BINARY=""
        for ((i=0; i<32; i++)); do
            if [ $i -lt $CIDR ]; then
                BINARY="${BINARY}1"
            else
                BINARY="${BINARY}0"
            fi
        done

        NETMASK=""
        for ((i=0; i<32; i+=8)); do
            BYTE=$((2#${BINARY:$i:8}))
            NETMASK+="$BYTE"
            if [ $i -lt 24 ]; then
                NETMASK+="."
            fi
        done
    fi
    
    cat > "$CHROOT_DIR/etc/network/interfaces" << EOF
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
    address $IP_ADDRESS
    netmask $NETMASK
    gateway $GATEWAY
EOF

    if [ -n "$DNS_SERVERS" ]; then
        echo "Configuring DNS servers: $DNS_SERVERS"
        mkdir -p "$CHROOT_DIR/etc/resolvconf/resolv.conf.d"
        
        echo "# Generated by kiosk builder" > "$CHROOT_DIR/etc/resolvconf/resolv.conf.d/base"
        
        IFS=',' read -ra DNS_ARRAY <<< "$DNS_SERVERS"
        for DNS in "${DNS_ARRAY[@]}"; do
            echo "nameserver $DNS" >> "$CHROOT_DIR/etc/resolvconf/resolv.conf.d/base"
        done

        cp "$CHROOT_DIR/etc/resolvconf/resolv.conf.d/base" "$CHROOT_DIR/etc/resolv.conf"
    fi
else
    echo "Error: Network type must be 'dhcp' or 'static'"
    exit 1
fi

echo "Network configuration completed successfully"
exit 0
